### ISSUE TITLE
Possible to add icons within zones as well?

### ISSUE THREAD

**Issue by smahm006** [fubaWoW/InstancePortalsAdv#1]
Hey thank you for making this addon!

Currently if I zoom out to the dragon isles I see all the dungeon locations and can interact with the icons. But once I click a specific zone, say The Waking Shores, then the dungeon icon disappears. 

Was wondering if zone specific icons are a possibility?

**Comment by fubaWoW** [comment]
have you tried this:
![image](https://user-images.githubusercontent.com/41425685/206853200-46a439ac-a4a5-44ad-9f2d-a8a8b90e031e.png)

**Comment by smahm006** [comment]
WoW did not know that options existed, thanks!
