### ISSUE TITLE
Error if u open more then 1 time any dngeon

### ISSUE THREAD

**Issue by Ssesmar** [fubaWoW/InstancePortalsAdv#3]
1x [ADDON_ACTION_FORBIDDEN] AddOn 'InstancePortalsAdv' hat versucht die geschützte Funktion 'OnOpen()' aufzurufen.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `OnOpen'
[string "@Blizzard_EncounterJournal/Blizzard_EncounterJournal.lua"]:587: in function <...zzard_EncounterJournal/Blizzard_EncounterJournal.lua:576>
[string "=[C]"]: in function `Show'
[string "@FrameXML/UIParent.lua"]:2943: in function `SetUIPanel'
[string "@FrameXML/UIParent.lua"]:2843: in function `ShowUIPanel'
[string "@FrameXML/UIParent.lua"]:2651: in function <FrameXML/UIParent.lua:2647>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML/UIParent.lua"]:3253: in function `ShowUIPanel'
[string "@Blizzard_EncounterJournal/Blizzard_EncounterJournal.lua"]:2422: in function `EncounterJournal_OpenJournal'
[string "@InstancePortalsAdv/IPAInstancePortalPinTemplate.lua"]:166: in function `OnClick'
[string "@Blizzard_MapCanvas/Blizzard_MapCanvas.lua"]:154: in function <...aceBlizzard_MapCanvas/Blizzard_MapCanvas.lua:151>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:486
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:486
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:486
}
event = "ADDON_ACTION_FORBIDDEN"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:552
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:552
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:546
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:561
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:506
}

**Comment by fubaWoW** [comment]
yeah it's blizzards fault... again... 👍

im already on a workaround ^^
will be released asap!

**Comment by fubaWoW** [comment]
got any more errors with the last version?
