### ISSUE TITLE
Overlapping text of IPA with PetTracker in the Map Filter options

### ISSUE THREAD

**Issue by KingDeVeteran** [fubaWoW/InstancePortalsAdv#4]
Hello there! Hope you're doing well, mate!

I have an issue / bug that I noticed recently (due to me rehauling my UI since I restarted playing):

The bug / issue in question happens due to how this addon interacts with Pet Tracker addon. 

When going into the map, then clicking on Map Filter to enable/disable certain things, your addons option of "Dungeons / Raids: Show on Continent Map" is overlapping with the text-options from Pet Tracker addon.

This is an issue that also the addon Plumber had, but the Plumber creator fixed it some time ago.

So that you may understand my problem as best as possible, I'll post a couple of links here to some material:

1. Pet Tracker addon (in case you don't know it): https://www.curseforge.com/wow/addons/pettracker

2. Plumber addon (in case you don't know it): https://www.curseforge.com/wow/addons/plumber

3. MOST IMPORTANT PIECE OF INFO: A github entry by someone showing the problematic interaction between Plumber and PetTracker addon before it was fixed: https://github.com/Jaliborc/PetTracker/issues/375

At no 3, in the github entry, you'll find screenshots of what the problem was. Basically, that overlap now happens only with your addon and Pet Tracker, Plumber doesn't have the issue anymore.

Hope you'll be able to fix this minor UI thing :) thank you and take care <3

**Comment by KingDeVeteran** [comment]
My OP was a copy-paste from my message on your Curse comments page, but here I see I can also post images myself, thus, first image from my client:

This screenshot represent an area from Elwynn Forest, thus, there is no WQ or Plumber options here, just Blizzard options, your option of dungeon on continents, and PetTracker options (the latter two being overlapped)
![Evidence 1](https://github.com/fubaWoW/InstancePortalsAdv/assets/136590216/aa66908a-ddc2-4852-9742-9a5eff7c4ca0)

**Comment by KingDeVeteran** [comment]
My second screenshot is from the Emerald Dream Dragonflight expansion, which has WQ options AND Plumber enabled as well here, they don't overlap, just your addon and Pet Tracker that overlap here as well :(
![Evidence 2](https://github.com/fubaWoW/InstancePortalsAdv/assets/136590216/1ea3ea8e-a155-4fa9-9b54-33c223f090ae)

**Comment by fubaWoW** [comment]
It is definitely Pet Tracker and their own bugged DropDown Menu!
I've already mentioned to remove that bugged DropDown Menu for YEARS now but they do not care.  
  
I will not try to fix this nor will i integrate my Setting into the bugged DropDown Mneu as of PetTracker also do not care to make it "properly" working!  
  
The only Way is to disable PetTracker while you not really need it or ignore the error.

Sorry, but i can not fix this.

**Comment by KingDeVeteran** [comment]
Thanks for the prompt response :) unfortunately, Pet Tracker is too valuable to just reload every now and then the UI for it. 

I've decided, sadly, to just remove Instance Portal Advanced and switch to the newly found addon HandyNotes_DungeonLocations and/or HandyNotes: MapNotes, still trying to figure out if I want the additional stuff or just the dungeon locations. The two HandyNotes modules also have the option to show the locations on the continent map + they have the options in the Interface - AddOn UI, not the Map Filter UI.

Again, thanks for your prompt response :) good luck and hope you have a great time in War Within ^_^
