### ISSUE TITLE
Instance Portals Advanced showing in settings menu multiple times

### ISSUE THREAD

**Issue by NoShotz** [fubaWoW/InstancePortalsAdv#5]
![image](https://github.com/user-attachments/assets/b09c3f5a-4ec5-40ed-859b-1b66b97e352c)

**Comment by fubaWoW** [comment]
hmm...
What Version?
Any Special Conditions?
Did you try with just IPA enabled?

I've tested now multiple Times without any AddOns (except IPA and my Debug Addons) looks like this for me:
![image](https://github.com/user-attachments/assets/a4a5a054-6bc1-40c6-b367-c04833399642)

and with ALL my **183** Addons active:
![image](https://github.com/user-attachments/assets/90fbe03b-4d14-4ef7-8937-64a3ae42465c)

**Comment by NoShotz** [comment]
The version is 110002.07-Release, so far it has only happened once, and I had all my various addons enabled, one thing to note, I didn't see any errors when this issue occurred.

**Comment by fubaWoW** [comment]
Does it still happen?

**Comment by NoShotz** [comment]
I just checked, and it has happened again, but I don't see any errors specifically mentioning this addon, one thing to note, it is on a character that hasn't had the latest version of the addon loaded before, could it potentially be related?

**Comment by fubaWoW** [comment]
No that should no matter because the Settings are Loaded from New every time you "Enter the World", then can be a Login or a Interface Reload.

But if there is some other Addon that trigger the "PLAYER_ENTERING_WORLD" event multiple times, this maybe can happen!

**Comment by fubaWoW** [comment]
i've pushed a new update [110002.08](https://github.com/fubaWoW/InstancePortalsAdv/commit/a50b2e58cf1cde6048d5ceca53dc92ca2f1a0092)
this will prevent from creating Settings Multiple Times, even if the event ``PLAYER_ENTERING_WORLD`` is triggered multiple times

But i would suggest to check all your AddOns, because this is not a "default" that events like ``PLAYER_ENTERING_WORLD`` is triggered multiple times and this can cause major Performance issues in some cases!

**Comment by Dathwada** [comment]
It is normal that the [PLAYER_ENTERING_WORLD](https://warcraft.wiki.gg/wiki/PLAYER_ENTERING_WORLD) event can be triggered multiple times.
> "Fires when the player logs in, /reloads the UI or zones between map instances. Basically whenever the loading screen appears."

I testet this on verison 110002.07 and if you use some portals to travel and the loading screen appears there will be a new menu entry.

I guess you want to use the [PLAYER_LOGIN](https://warcraft.wiki.gg/wiki/PLAYER_LOGIN) event instead:
> Triggered immediately before [PLAYER_ENTERING_WORLD](https://warcraft.wiki.gg/wiki/PLAYER_ENTERING_WORLD) on login and UI Reload, but NOT when entering/leaving instances.

**Comment by NoShotz** [comment]
Makes sense, I was going through portals doing the pre-patch event.

**Comment by fubaWoW** [comment]
> It is normal that the [PLAYER_ENTERING_WORLD](https://warcraft.wiki.gg/wiki/PLAYER_ENTERING_WORLD) event can be triggered multiple times.
> 
> > "Fires when the player logs in, /reloads the UI or zones between map instances. Basically whenever the loading screen appears."
> 
> I testet this on verison 110002.07 and if you use some portals to travel and the loading screen appears there will be a new menu entry.
> 
> I guess you want to use the [PLAYER_LOGIN](https://warcraft.wiki.gg/wiki/PLAYER_LOGIN) event instead:
> 
> > Triggered immediately before [PLAYER_ENTERING_WORLD](https://warcraft.wiki.gg/wiki/PLAYER_ENTERING_WORLD) on login and UI Reload, but NOT when entering/leaving instances.

well...
you're totally right!

don't know why i did this mistake 🤷‍♂️

I know the ``PLAYER_LOGIN`` event and also everything else in the [AddOn loading process](https://warcraft.wiki.gg/wiki/AddOn_loading_process), but... hey... stupid me! 🤦‍♂️ 🤣

i will update this later!

Thanks for the hint! 👌
