### ISSUE TITLE
[Feature request] Mimic Blizzard POI behavior

### ISSUE THREAD

**Issue by Dathwada** [fubaWoW/InstancePortalsAdv#6]
Hi, would it be possible that the continent POIs mimic the behavior of Blizzard's original dungeon entrance POIs?

Now it will create the Map Pin over the icon.
![continent](https://github.com/user-attachments/assets/e7bd4a53-7d3f-4ef8-b139-7f6594235f88)

Blizzards shows the "SuperTrackMarker" on the POI icon and if I click the POI again it will remove it.
![zone](https://github.com/user-attachments/assets/84781830-f55e-45d6-a9be-9307f7aa09e8)

This might help you to implement it.
[SharedMapPoiTemplates.lua](https://github.com/BigWigsMods/WoWUI/blob/abae8d299f35445ff5498ff0ccee29af25c4daa9/AddOns/Blizzard_SharedMapDataProviders/SharedMapPoiTemplates.lua#L469)
[SharedMapPoiTemplates.xml](https://github.com/BigWigsMods/WoWUI/blob/abae8d299f35445ff5498ff0ccee29af25c4daa9/AddOns/Blizzard_SharedMapDataProviders/SharedMapPoiTemplates.xml#L32)

**Comment by fubaWoW** [comment]
Yes, this is already on my todo list!
But i don't know when it've the Time to make.

**Comment by fubaWoW** [comment]
done in https://github.com/fubaWoW/InstancePortalsAdv/commit/71f0668498fe367736ef800be7b205845a5e0457
