### ISSUE TITLE
Button:SetPassThroughButtons() error

### ISSUE THREAD

**Issue by masterkain** [fubaWoW/InstancePortalsAdv#7]
```
1x [ADDON_ACTION_BLOCKED] AddOn 'InstancePortalsAdv' tried to call the protected function 'Button:SetPassThroughButtons()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `SetPassThroughButtons'
[string "@Blizzard_MapCanvas/MapCanvas_DataProviderBase.lua"]:224: in function `CheckMouseButtonPassthrough'
[string "@Blizzard_MapCanvas/Blizzard_MapCanvas.lua"]:209: in function `AcquirePin'
[string "@Blizzard_SharedMapDataProviders/QuestDataProvider.lua"]:229: in function `AddQuest'
[string "@Blizzard_SharedMapDataProviders/QuestDataProvider.lua"]:163: in function `CheckAddQuest'
[string "@Blizzard_SharedMapDataProviders/QuestDataProvider.lua"]:174: in function `RefreshAllData'
[string "@Blizzard_SharedMapDataProviders/QuestDataProvider.lua"]:41: in function <...lizzard_SharedMapDataProviders/QuestDataProvider.lua:41>
[string "=[C]"]: ?
[string "@Blizzard_SharedXMLBase/CallbackRegistry.lua"]:144: in function <...eBlizzard_SharedXMLBase/CallbackRegistry.lua:143>
[string "=[C]"]: ?
[string "@Blizzard_SharedXMLBase/CallbackRegistry.lua"]:147: in function `TriggerEvent'
[string "@Blizzard_FrameXMLUtil/Mainline/Blizzard_QuestSuperTracking.lua"]:59: in function `CacheCurrentSuperTrackInfo'
[string "@Blizzard_FrameXMLUtil/Mainline/Blizzard_QuestSuperTracking.lua"]:17: in function <...rameXMLUtil/Mainline/Blizzard_QuestSuperTracking.lua:15>

Locals:
_ = Frame {
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
}
```

I'm not entirely sure if it's the addon erroring out or blizzard bug

**Comment by fubaWoW** [comment]
no it is not my addon (i do not hook any blizzard stuff, just add something) and also not blizzard bug
any addon you have installed "Taints" the game

But...
Try Original interface (no other addons) but just "InstancePortalsAdv" installed and enabled and see if the error pops again?

**Comment by masterkain** [comment]
I'll try but I'm not sure how to reproduce the bug, thanks in the meantime!

**Comment by fubaWoW** [comment]
Yes i know, i have the same error and it comes form... i don't know yet 🤣

If i have time i will figure out what triggers the error and then i can figure out what addon it is.

But i've installed 200+ addons and 150 of them are active most of the time, yeah... i'm sick.. i know 😁

But, please...
if you know or figure out what addon cause this, please let mi know!

BTW i suggest to use the AddOn [TaintLess](https://www.townlong-yak.com/addons/taintlessrl) from townlong-yak.
They sometimes fix certain bugs!
